spring:
  application:
    name: ai-sandbox
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  config:
    import: optional:file:.env[.properties]
  ai:
    retry:
      max-attempts: 3
    gigachat:
      scope: GIGACHAT_API_PERS
      client-id: ${GIGACHAT_API_CLIENT_ID}
      client-secret: ${GIGACHAT_API_CLIENT_SECRET}
      unsafe-ssl: true
      chat:
        options:
          model: GigaChat
    ollama:
      chat:
        model: gemma3:4b
        options:
          temperature: 0.5 # default 0.8
          num-predict: 128 # default 128
          top-k: 20 # default 40

server:
  port: 8088
  servlet:
    context-path: /api
    encoding:
      force: true
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    chat.giga.springai.api.chat: DEBUG
